# Generated by Django 5.0.1 on 2024-01-10 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_personal', models.CharField(max_length=70)),
                ('foto_personal', models.ImageField(upload_to='personal')),
                ('enlace_contacto_1', models.URLField(max_length=255)),
                ('enlace_contacto_2', models.URLField(blank=True, max_length=255, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'personal',
                'verbose_name_plural': 'personales',
            },
        ),
    ]
